version: "3.8"

services:
  workflow-engine:
    image: 192.168.12.101:5000/workflow-engine:1.0.8
    ports:
      - "7000:3000"   # change if your app listens on another port
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
